### ISSUE TITLE
Regarding php-auto-yasnippets

### ISSUE THREAD

**Issue by ejmr** [emacs-php/php-suite#1]
Firstly, I love the idea of collecting useful PHP-related Emacs packages into one place.

Secondly, today I deleted and/or archived many of my GitHub repositories, and [the repository for automatic YASnippets of PHP functions](https://github.com/ejmr/php-auto-yasnippets) was one of those repositories.  I only archived it, as I know at least a few people still use it, and deleting it would most likely caused them problems.  Archiving it means that users can still view the project page, read all existing issues, create forks, et cetera.  But no more development can take place in that repository.

Therefore, if you think [php-auto-yasnippets](https://github.com/ejmr/php-auto-yasnippets) would be a useful addition to this suite, then it deserves a fork so that anyone in the @emacs-php group can work on it if they want to.

Finally, keep up all the great work!

**Comment by zonuexe** [comment]
@ejmr Thank you for your suggestion.
By transferring the repository to the organization, we can take over it for maintenance.
Recently @Fuco1 [proposed to transfer a repository](https://github.com/emacs-php/emacs-nette-tester/issues/2), so do not hesitate to do the same.

Since you have ownership of this organization, please transfer the repository to this organization at any time. I will do maintenance of it (such as necessary modifications for future Emacs and acceptance of pull-request).

**Comment by ejmr** [comment]
Today I transfered the [php-auto-yasnippets](https://github.com/ejmr/php-auto-yasnippets) to the @emacs-php organization.  Please take any steps you believe are necessary to info users that my presonal fork of the project is no longer the "definitive" version, and that all work should go to the fork owned by @emacs-php.

**Comment by ejmr** [comment]
@zonuexe Even on the list of @emacs-php repositories, the repo for PHP Auto YASnippets still has the "archived" label.  If this causes a problem, e.g. it is archived and users cannot do anything like open issues or submit pull-requests, then please let me know and I will un-archive the repository.  You should have the authority to un-archive it yourself, but I am not one-hundred percent sure based on what I read in the GitHub help files.

**Comment by Fuco1** [comment]
@ejmr I can confirm that it is possible to unarchive it for this group.

Your personal fork is not really a fork but a redirect github maintains to keep old remotes working.  It all points to the project in emacs-php group.

**Comment by ejmr** [comment]
@Fuco1 Ah, good to know.  Thank you for the info.

**Edit:** Exactly as I anticipated, it looks like @zonuexe has found great people to help continue to improve the lives of PHP developers using GNU Emacs.  After reading some of your work, prompted by [a previously mentioned issue](https://github.com/emacs-php/emacs-nette-tester/issues/2), I am happy that USAMI Kenta has brought you into the fold.
